Revert "Add an optional acceptedOn field to trades (#29)"
This reverts commit 543f43c25e4a893cff754d50df4bb1f719b1cb78.

diff --git a/.github/workflows/continuous-deployment.yml b/.github/workflows/continuous-deployment.yml
--- a/.github/workflows/continuous-deployment.yml
+++ b/.github/workflows/continuous-deployment.yml
@@ -39,9 +39,9 @@ jobs:
         with:
           command: c
           files: |
-            ./.tool-versions
             ./declarations
             ./dist
+            ./.tool-versions
             ./ormconfig.js
             ./tsconfig.json
             ./package.json
@@ -99,13 +99,12 @@ jobs:
           password: ${{ secrets.PASSWORD }}
           port: ${{ secrets.SSH_PORT }}
           script: |
-            MIGRATION_UUID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
             cd /opt/Apps/TradeMachine
-            /home/dev_deployer/.asdf/shims/npx typeorm migration:generate -f ormconfig -c production -n "$MIGRATION_UUID"
-            sh check_migrations.sh $MIGRATION_UUID
+            /home/dev_deployer/.asdf/shims/npx typeorm migration:generate -f ormconfig -c production -n "autogen"
+#            sh check_migrations.sh
 
       - name: Run migrations if needed
-        if: ${{ failure() }}
+#        if: ${{ failure() }}
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
@@ -113,7 +112,7 @@ jobs:
           password: ${{ secrets.PASSWORD }}
           port: ${{ secrets.SSH_PORT }}
           script: |
-            echo "last command returned: $?"
+            echo $?
             cd /opt/Apps/TradeMachine
             /home/dev_deployer/.asdf/shims/npx typeorm migration:run -f ormconfig -c production
 
